from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.domain.schemas.entities import AttemptCreate, AttemptUpdate


class AttemptSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")


class AttemptRead(BaseModel):
    model_config = ConfigDict(extra="allow")

    attempt_id: UUID | None = None
    exam_id: UUID | None = None
    user_id: UUID | None = None
    score: float | None = None
    status: str | None = None
    created_at: str | None = None
    completed_at: str | None = None
    started_at: str | None = None
    spent_time: int | None = None


class AttemptResponse(AttemptSchema):
    data: AttemptRead


class AttemptListResponse(AttemptSchema):
    data: list[AttemptRead]
    limit: int
    offset: int


class AttemptListRequest(AttemptSchema):
    limit: int = Field(default=100, ge=1, le=500)
    offset: int = Field(default=0, ge=0)


class AttemptPath(AttemptSchema):
    attempt_id: UUID


class AttemptCreateRequest(AttemptSchema):
    payload: AttemptCreate


class AttemptUpdateRequest(AttemptSchema):
    attempt_id: UUID
    payload: AttemptUpdate


class AttemptDeleteRequest(AttemptSchema):
    attempt_id: UUID


class AttemptRepositoryListRequest(AttemptListRequest):
    pass


class AttemptRepositoryGetRequest(AttemptPath):
    pass


class AttemptRepositoryCreateRequest(AttemptCreateRequest):
    pass


class AttemptRepositoryUpdateRequest(AttemptUpdateRequest):
    pass


class AttemptRepositoryDeleteRequest(AttemptDeleteRequest):
    pass


class StartAttemptRequest(AttemptSchema):
    """Empty command model: server derives user, score, status and timestamps."""


class SubmitAttemptAnswerRequest(AttemptSchema):
    selected_option_id: UUID | None = None
    answer_text: str | None = Field(default=None, min_length=1, max_length=10_000)

    @model_validator(mode="after")
    def validate_answer_value(self) -> "SubmitAttemptAnswerRequest":
        has_option = self.selected_option_id is not None
        has_text = self.answer_text is not None
        if has_option == has_text:
            raise ValueError("Debe enviar una opcion seleccionada o una respuesta de texto, no ambas.")
        return self


class FinishAttemptRequest(AttemptSchema):
    """Empty command model: grading values are always generated by the server."""


class AttemptQuestionOptionRead(AttemptSchema):
    option_id: UUID
    option_text: str
    option_order: int


class AttemptQuestionRead(AttemptSchema):
    question_id: UUID
    type: str
    statement: str
    question_order: int
    points: float
    options: list[AttemptQuestionOptionRead] = Field(default_factory=list)


class SubmittedAttemptAnswerRead(AttemptSchema):
    answer_id: UUID
    attempt_id: UUID
    question_id: UUID
    selected_option_id: UUID | None = None
    answer_text: str | None = None
    is_correct: bool | None = None
    points_awarded: float | None = Field(default=None, ge=0)
    created_at: datetime | None = None


class AttemptSessionRead(AttemptSchema):
    attempt_id: UUID
    exam_id: UUID
    status: str
    started_at: datetime | None = None
    questions: list[AttemptQuestionRead]
    answers: list[SubmittedAttemptAnswerRead] = Field(default_factory=list)


class AttemptSessionResponse(AttemptSchema):
    data: AttemptSessionRead


class SubmittedAttemptAnswerResponse(AttemptSchema):
    data: SubmittedAttemptAnswerRead


class GradedAttemptAnswerRead(AttemptSchema):
    answer_id: UUID
    question_id: UUID
    is_correct: bool
    points_awarded: float = Field(ge=0)
    confidence: float | None = Field(default=None, ge=0, le=1)
    feedback: str | None = None


class FinishedAttemptRead(AttemptSchema):
    attempt_id: UUID
    exam_id: UUID
    status: str
    score: float = Field(ge=0, le=100)
    earned_points: float = Field(ge=0)
    total_points: float = Field(ge=0)
    answered_questions: int = Field(ge=0)
    total_questions: int = Field(ge=0)
    completed_at: datetime
    spent_time: int = Field(ge=0)
    answers: list[GradedAttemptAnswerRead] = Field(default_factory=list)


class FinishedAttemptResponse(AttemptSchema):
    data: FinishedAttemptRead
